/**
 * Projects editorial card records into the runtime shape the app already
 * consumes.
 *
 * The editorial record is canonical; the runtime record is a projection of it.
 * It deliberately keeps the app's existing field names (`quote`, `person`,
 * `authentic`, `contentState`) so RoundScreen, ReviewScreen, validateDeck and
 * isPlayableCard keep working untouched — renaming to statementText/displayName
 * would churn six components for no behavioural gain.
 *
 * Everything editorial is stripped: notes, citations, rubric scores and
 * calibration counts never reach a device.
 */

import { createHash } from "node:crypto";

/**
 * Unify typography across BOTH classes before emitting.
 *
 * Curly quotes and ellipsis characters are a copy-paste provenance signature,
 * not a voice trait: text pasted from an article keeps the outlet's smart
 * quotes and text typed by an editor does not, which makes them a near-perfect
 * authenticity marker for any player who notices. Normalising only the
 * authentic side would swap one tell for another, so it applies to everything.
 *
 * This is not the same as "correcting" a quote — casing, spelling, grammar and
 * word choice are untouched, because those are the authenticity texture the
 * rubric forbids editing.
 */
export function normalizeTypography(text) {
  return String(text)
    .replace(/[’‘]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/\.\.\./g, "…")
    .replace(/&amp;/g, "&")
    .replace(/\s+$/g, "");
}

/**
 * Editorial state → runtime contentState. This table is the whole three-shape
 * bridge; isPlayableCard needs no change because it already demands exactly
 * what the "authentic" row produces.
 *
 * Order matters: removal and dispute win over authenticity, so a card that was
 * taken down cannot come back as playable through the authentic branch.
 */
export function deriveContentState(card) {
  if (card.removalStatus === "removed") return "removed";
  if (card.disputed === true) return "disputed";
  if (card.authenticity === "fabricated") return "fabricated-for-game";
  const source = card.source;
  const hasRetainedHttps =
    source?.retained === true && typeof source.url === "string" && source.url.startsWith("https://");
  return hasRetainedHttps ? "authentic" : "source-unavailable";
}

export function toRuntimeCard(card) {
  const contentState = deriveContentState(card);
  const approvals = Array.isArray(card.editorialApprovals)
    ? [...new Set(card.editorialApprovals.filter((e) => e?.decision !== "reject").map((e) => e?.editor ?? e))]
    : [];

  const runtime = {
    id: card.id,
    quote: normalizeTypography(card.statementText),
    person: card.displayName,
    authentic: contentState === "authentic",
    contentState,
    explanation: card.explanation,
    editorialApprovals: approvals,
    category: card.category,
    sensitivity: card.sensitivity,
    decoyMethod: card.decoyMethod,
    tier: card.status,
  };

  if (contentState === "authentic") {
    runtime.sourceRecord = { retained: true, url: card.source.url };
  }
  return runtime;
}

export function buildBundle({ manifest, cards }) {
  const runtime = cards.map(toRuntimeCard);
  // Stable order so the emitted file only changes when the content does.
  runtime.sort((a, b) => a.id.localeCompare(b.id));
  return {
    deckVersion: manifest.contentVersion,
    cards: runtime,
    tombstones: [...(manifest.tombstones ?? [])].sort(),
  };
}

export function sourceChecksum({ manifest, cards }) {
  const canonical = JSON.stringify({
    manifest,
    cards: [...cards].sort((a, b) => String(a.id).localeCompare(String(b.id))),
  });
  return createHash("sha256").update(canonical).digest("hex");
}

export function renderBundleModule(bundle, checksum) {
  return `/**
 * GENERATED by tools/content-pipeline/bin/build.mjs — do not edit by hand.
 *
 * Regenerate with:
 *   node tools/content-pipeline/bin/build.mjs --deck pop-voices
 *
 * Every card here passed the editorial gates in tools/content-pipeline: Tier
 * A/B provenance, two distinct approvals, and the safety, read-aloud,
 * composition and tell-leakage checks. Editing this file by hand bypasses all
 * of them.
 */
export const GENERATED_DECK_VERSION = ${JSON.stringify(bundle.deckVersion)};
export const GENERATED_SOURCE_SHA256 = ${JSON.stringify(checksum)};

export const generatedCards = ${JSON.stringify(bundle.cards, null, 2)};

export const generatedTombstones = ${JSON.stringify(bundle.tombstones, null, 2)};
`;
}
