import { StyleSheet } from "react-native";

import { tokens as t } from "../theme/tokens";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: t.color.canvas },
  app: { flex: 1, padding: t.spacing.md },
  header: { flexDirection: "row", justifyContent: "space-between", paddingTop: t.spacing.xs },
  brand: { color: t.color.text.primary, fontWeight: t.typography.weight.bold, letterSpacing: 1.5 },
  score: { color: t.color.signal, fontSize: t.typography.size.beacon, fontWeight: t.typography.weight.bold },
  center: { flex: 1, justifyContent: "center", gap: t.spacing.sm },
  setup: { flexGrow: 1, justifyContent: "center", gap: t.spacing.sm, paddingVertical: t.spacing.md + t.spacing.xs },
  eyebrow: { color: t.color.signal, fontSize: t.typography.size.beacon, fontWeight: t.typography.weight.bold, letterSpacing: 1.4 },
  title: { color: t.color.text.primary, fontSize: t.typography.size.statement + 6, fontWeight: t.typography.weight.bold, lineHeight: t.typography.size.statement + 11 },
  copy: { color: t.color.text.muted, fontSize: t.typography.size.body, lineHeight: t.typography.size.body + 6 },
  note: { color: t.color.text.muted, fontSize: t.typography.size.beacon + 2, lineHeight: t.typography.size.beacon + 8 },
  fixture: { color: t.color.status.warning, fontSize: t.typography.size.beacon, fontWeight: t.typography.weight.bold, letterSpacing: 0.8 },
  button: { backgroundColor: t.color.action.primary, minHeight: t.target.minimum, justifyContent: "center", alignItems: "center", paddingHorizontal: t.spacing.sm + 2, borderRadius: t.radius.control },
  buttonText: { color: t.color.canvas, fontSize: t.typography.size.body, fontWeight: t.typography.weight.bold, textAlign: "center" },
  secondary: { backgroundColor: "transparent", borderWidth: 2, borderColor: t.color.text.primary },
  secondaryText: { color: t.color.text.primary },
  disabled: { opacity: 0.55 },
  link: { color: t.color.text.primary, textAlign: "center", fontWeight: t.typography.weight.semibold, padding: t.spacing.xs + 2 },
  choice: { borderWidth: 2, borderColor: t.color.action.secondary, padding: t.spacing.sm + 2, borderRadius: t.radius.control, gap: 6 },
  choiceActive: { borderColor: t.color.signal, backgroundColor: t.color.surface },
  choiceTitle: { color: t.color.text.primary, fontSize: t.typography.size.body + 3, fontWeight: t.typography.weight.bold },
  choiceBody: { color: t.color.text.muted, fontSize: t.typography.size.body - 3, lineHeight: t.typography.size.body + 3 },
  sectionLabel: { color: t.color.signal, fontSize: t.typography.size.beacon + 1, fontWeight: t.typography.weight.bold, letterSpacing: 1 },
  round: { flex: 1, paddingTop: t.spacing.lg - 4, gap: t.spacing.sm },
  mode: { color: t.color.signal, fontWeight: t.typography.weight.bold, letterSpacing: 1 },
  beacon: { borderTopWidth: 4, borderBottomWidth: 4, borderColor: t.color.signal, paddingVertical: t.spacing.xs },
  game: { color: t.color.text.primary, fontWeight: t.typography.weight.bold, letterSpacing: 1, textAlign: "center", fontSize: t.typography.size.beacon },
  card: { flexGrow: 1, justifyContent: "center", gap: t.spacing.sm },
  quote: { color: t.color.text.primary, fontSize: t.typography.size.statement + 4, fontWeight: t.typography.weight.bold, lineHeight: t.typography.size.statement + 11 },
  person: { color: t.color.text.muted, fontSize: t.typography.size.body + 2, fontWeight: t.typography.weight.semibold },
  instruction: { color: t.color.text.muted, fontSize: t.typography.size.body - 2, lineHeight: t.typography.size.body + 4 },
  actions: { gap: t.spacing.sm - 4 },
  report: { borderTopWidth: 1, borderColor: t.color.action.secondary, paddingTop: t.spacing.sm + 2, gap: t.spacing.sm - 4 },
  success: { color: t.color.status.safe, fontSize: t.typography.size.beacon + 2, lineHeight: t.typography.size.beacon + 8 },
  error: { color: t.color.status.danger, fontSize: t.typography.size.beacon + 2, lineHeight: t.typography.size.beacon + 8 },
});
